export type EventSeverity = 'INFO' | 'WARNING' | 'CRITICAL';

export type MonitoringEventType =
  | 'VERIFICATION_REQUESTED'
  | 'VERIFICATION_COMPLETED'
  | 'VERIFICATION_FAILED'
  | 'EVIDENCE_CAPTURED'
  | 'EVIDENCE_UPLOADED'
  | 'DEVICE_NO_SIGNAL'
  | 'SATELLITE_SCENE_INGESTED'
  | 'ALERT_RAISED'
  | 'GUARANTEE_CONFIRMED'
  | 'MONITORING_SCHEDULED';
